server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - name: AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
            - AddRequestHeader=Content-Type, application/json
          filters:
            - name: AuthenticationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: AuthenticationFilter