server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**